import re

from nltk.tokenize import sent_tokenize, word_tokenize


def analyze_with_nltk(text: str) -> dict:
    """
    Extract basic linguistic features using NLTK.

    Required NLTK tokenizer resources should be installed
    during environment setup, not downloaded during requests.

    These features are supporting signals only.
    They do not prove that text was generated by AI.
    """

    if not text or not text.strip():
        return {
            "nltk_sentence_count": 0,
            "nltk_word_count": 0,
            "nltk_average_word_length": 0.0,
            "nltk_unique_word_ratio": 0.0,
            "nltk_long_word_ratio": 0.0,
        }

    sentences = sent_tokenize(text)

    words = word_tokenize(text)

    words = [
        word.lower()
        for word in words
        if re.fullmatch(r"[a-zA-Z]+", word)
    ]

    word_count = len(words)

    if word_count == 0:
        return {
            "nltk_sentence_count": len(sentences),
            "nltk_word_count": 0,
            "nltk_average_word_length": 0.0,
            "nltk_unique_word_ratio": 0.0,
            "nltk_long_word_ratio": 0.0,
        }

    average_word_length = (
        sum(len(word) for word in words)
        / word_count
    )

    unique_word_ratio = (
        len(set(words))
        / word_count
    )

    long_word_ratio = (
        sum(
            1
            for word in words
            if len(word) >= 8
        )
        / word_count
    )

    return {
        "nltk_sentence_count": len(sentences),
        "nltk_word_count": word_count,
        "nltk_average_word_length": round(
            average_word_length,
            2,
        ),
        "nltk_unique_word_ratio": round(
            unique_word_ratio,
            4,
        ),
        "nltk_long_word_ratio": round(
            long_word_ratio,
            4,
        ),
    }