import math

try:
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    HEAVY_MODEL_AVAILABLE = True
except ImportError:
    torch = None
    AutoModelForCausalLM = None
    AutoTokenizer = None
    HEAVY_MODEL_AVAILABLE = False


MODEL_NAME = "distilgpt2"

_tokenizer = None
_model = None


def load_model():
    global _tokenizer
    global _model

    if not HEAVY_MODEL_AVAILABLE:
        return None, None

    if _tokenizer is None or _model is None:
        _tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
        _model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)

        _model.eval()

    return _tokenizer, _model


def calculate_perplexity(text: str) -> dict:
    """
    Calculate language-model perplexity using DistilGPT-2.

    Perplexity is an optional supporting signal.
    It is not proof that text was generated by AI.

    If PyTorch/Transformers are unavailable, the main
    candidate-analysis pipeline continues without perplexity.
    """

    if not text or not text.strip():
        return {
            "perplexity": None,
            "perplexity_available": False,
        }

    if not HEAVY_MODEL_AVAILABLE:
        return {
            "perplexity": None,
            "perplexity_available": False,
        }

    try:
        tokenizer, model = load_model()

        if tokenizer is None or model is None:
            return {
                "perplexity": None,
                "perplexity_available": False,
            }

        encoded = tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            max_length=512,
        )

        input_ids = encoded["input_ids"]

        if input_ids.shape[1] < 2:
            return {
                "perplexity": None,
                "perplexity_available": False,
            }

        with torch.no_grad():
            outputs = model(
                input_ids,
                labels=input_ids,
            )

        loss = outputs.loss

        perplexity = math.exp(
            min(float(loss), 20)
        )

        return {
            "perplexity": round(perplexity, 2),
            "perplexity_available": True,
        }

    except Exception as exc:
        return {
            "perplexity": None,
            "perplexity_available": False,
            "perplexity_error": str(exc),
        }